### PR TITLE
Update Discovery API Version

### PR DESCRIPTION
**Pull request by justinmccoy**
The API version for the Discovery service utilized depreciated APIs and prevented users from uploading new documents to the discovery collection.  This new API version fixes the issue.

### CODE REVIEW

**Comment by stevemart** [comment]
@justinmccoy was there an error or warning message being generated?

**Comment by markstur** [comment]
The current version works fine for me (uploads docs).

**Comment by markstur** [comment]
Updated. I don't see any difference. I suspect there was confusion about known errors w/ Discovery that require restarts and perhaps it just seemed like this fixed something.  But since I was testing anyway, I figure it is better to be on the newer version.

**Comment by justinmccoy** [comment]
Good to remove all the depreciated API warnings :)

**Pull request merged**
